//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsientoContable()
        {
            this.AsientoCuenta = new HashSet<AsientoCuenta>();
        }
    
        public int idAsientoContable { get; set; }
        public string Descripcion { get; set; }
        public int idAuxiliar { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Auxiliar Auxiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientoCuenta> AsientoCuenta { get; set; }
    }
}
