//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoCuenta
    {
        public int idAsientoContable { get; set; }
        public int idCuentaContable { get; set; }
        public double Monto { get; set; }
        public string tipoMov { get; set; }
    
        public virtual AsientoContable AsientoContable { get; set; }
        public virtual CuentaContable CuentaContable { get; set; }
    }
}
