//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaContable()
        {
            this.CuentaContable1 = new HashSet<CuentaContable>();
        }
    
        public int idCuentaContable { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> idTipoCuenta { get; set; }
        public bool PermiteTrans { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> CtaMayor { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Estado { get; set; }
    
        public virtual TipoCuenta TipoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaContable> CuentaContable1 { get; set; }
        public virtual CuentaContable CuentaContable2 { get; set; }
    }
}
